spring:
  datasource:
    url: jdbc:mysql://cnergy-db.crqg2s8ywswf.ap-northeast-2.rds.amazonaws.com/cnergy
    username: admin
    password: PEioD27vEVsrGyO
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      platform: mysql
      mode: always
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true