name: Cnergy Backend CD

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - name: 아티팩트 다운로드
        uses: actions/download-artifact@v2
        with:
          name: image_tag

      - name : 태그 환경변수 저장
        id: set_tag
        run: echo "IMAGE_TAG=$(cat image_tag.txt)" >> $GITHUB_ENV

      - name : NCP 서버 접속
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.NCP_HOST }}
          username: ${{ secrets.NCP_USERNAME }}
          password: ${{ secrets.NCP_PASSWORD }}
          port: ${{ secrets.NCP_PORT }}
          script: |
            sudo chmod +x ./deploy.sh
            export NCP_CONTAINER_REGISTRY=${{ secrets.NCP_CONTAINER_REGISTRY }}
            export IMAGE_TAG=$(cat image_tag.txt)
            ./deploy.sh
