name: Cnergy Backend CD

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - name : NCP 서버 접속
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.NCP_HOST }}
          username: ${{ secrets.NCP_USERNAME }}
          password: ${{ secrets.NCP_PASSWORD }}
          port: ${{ secrets.NCP_PORT }}
          script: |
            sudo chmod +x ./deploy.sh
            sudo docker rm -f $(docker ps -qa) || true
            export NCP_CONTAINER_REGISTRY=${{ secrets.NCP_CONTAINER_REGISTRY }}
            export GITHUB_SHA=${{ github.sha }}
            ./deploy.sh
